name: innova
description: "Innova proyecto"

publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ^3.7.2

dependencies:
  flutter:
    sdk: flutter
  intl: ^0.19.0
  device_preview: 1.2.0
  shared_preferences: ^2.2.2
  image_picker: ^1.0.4

  cupertino_icons: ^1.0.8
  firebase_core: ^3.6.0
  firebase_auth: ^5.3.1
  http: any
  flutter_launcher_icons: ^0.14.3
dev_dependencies:
  flutter_test:
    sdk: flutter
flutter_icons:
  android: true
  ios: true
  image_path: "assets/images/LogSeg.jpg"



  flutter_lints: ^5.0.0


flutter:


  uses-material-design: true

